[package]
name = "seq"
version = "0.0.0"
edition = "2021"
autotests = false
publish = false

[[test]]
name = "tests"
path = "tests/progress.rs"

[dev-dependencies]
trybuild = { version = "1.0.49", features = ["diff"] }

[dependencies]
proc-macro-hack = "0.5"
seq-proc = { path = "seq-proc/" }
